baseURL = "https://gozette.fr"
RelativeURLs=true
CanonifyURLs=true
title = "La Gozette du senté"
author = ""
copyright = ""
paginate = 12
languageCode = "fr"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
disqusShortname = "gozette"

theme = "casper3"

[params]
  # facebook = "https://facebook.com"
  # twitter = "https://twitter.com"
  # github = "https://github.com/jonathanjanssens"
  description = ""
  mainSections = ["posts"]

[menu]

  [[menu.main]]
    identifier = "numeros"
    name = "Numéros"
    url = "/numeros/"
    weight = 8

  [[menu.main]]
    identifier = "dossiers"
    name = "Dossiers"
    url = "/categories/dossier/"
    weight = 7

  [[menu.main]]
    identifier = "contributors"
    name = "Contributeurs"
    url = "/author/"
    weight = 9

  [[menu.main]]
    identifier = "about"
    name = "A Propos"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  numero = "numeros"
  author = "author"

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true